name: Build and publish release packages
permissions:
  contents: write
on:
  release:
    types: [created]

jobs:
  build-x86_64-linux-binaries:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y gcc-multilib llvm llvm-dev libclang-dev clang cmake protobuf-compiler
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Build and publish
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: qdrant
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-aarch-linux-binaries:
      strategy:
        matrix:
          include:
            - target: aarch64-unknown-linux-gnu
              os: ubuntu-latest
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            target: ${{ matrix.target }}
        - uses: actions/checkout@v3
        - name: Install cross
          run: cargo install cross
          shell: bash
        - name: configure Cross.toml
          run: |
              echo -e "[target.aarch64-unknown-linux-gnu]\npre-build = \"./dependency.sh\"" >> ./Cross.toml
              echo -e "apt-get update; apt-get install -y gcc-aarch64-linux-gnu llvm-dev libclang-dev clang cmake protobuf-compiler" > ./dependency.sh
              chmod 777 ./dependency.sh
          shell: bash    
        - name: Build
          run: cross build --release --target ${{ matrix.target }}
        - uses: taiki-e/upload-rust-binary-action@v1
          with:
            bin: qdrant
            target: ${{ matrix.target }}
            token: ${{ secrets.GITHUB_TOKEN }}

  build-mac-binaries:
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: |
            brew update
            brew install gcc llvm cmake protobuf-c
      - uses: actions/checkout@v3
      - name: Build and publish
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: qdrant
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
  build-windows-binaries:
    strategy:
      matrix:
        include:
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install minimal stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: cargo build --release
      - name: Build and publish
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: qdrant
          token: ${{ secrets.GITHUB_TOKEN }}
