name: Build and publish release packages

on:
  release:
    types: [created]

jobs:
  install-dependencies:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86, arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y gcc-multilib
            sudo apt-get install -y clang cmake protobuf-compiler
  upload-assets:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86, arm64]
        bin: [qdrant]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3e
      - name: Build and publish
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ matrix.bin }}
          target: ${{ matrix.arch }}-unknown-linux-gnu
          token: ${{ secrets.GITHUB_TOKEN }}
